definitions:
  service.requestCreateOneTask:
    properties:
      created_at:
        type: string
      done:
        type: boolean
      id:
        type: integer
      subtitle:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  service.responseCreateOneTask:
    properties:
      created_at:
        type: string
      done:
        type: boolean
      id:
        type: integer
      subtitle:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  service.responseCreateOneTaskErr:
    properties:
      error:
        type: string
    type: object
  service.responseGetHello:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: letung3105@gmail.com
    name: Tung L. Vo
    url: https://github.com/letung3105
  license:
    name: MIT
    url: https://mit-license.org
paths:
  /hello:
    get:
      description: trả về chuỗi kí tự "Hello World"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.responseGetHello'
      summary: Hello world
  /todo:
    post:
      consumes:
      - application/json
      description: tạo một tác vụ mới
      parameters:
      - description: tác vụ được thêm vào
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/service.requestCreateOneTask'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.responseCreateOneTask'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/service.responseCreateOneTaskErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.responseCreateOneTaskErr'
      summary: Create one task
swagger: "2.0"
